name: 'Run Robocorp Cloud robot'
description: 'Run a Robocorp Cloud robot and wait for the result'
inputs:
  process-secret:
    description: 'Process API access secret key'
    required: true
  process-url:
    description: 'Process trigger URL'
    required: true
  payload:
    description: JSON payload for the robot
  timeout:
    description: The max time to run the action (in seconds)
    required: false
    default: '120'
runs:
  using: 'node12'
  main: 'index.js'
